### ISSUE TITLE
normalize GMC identity fields with ES identity fields as possible

### ISSUE THREAD

**Issue by DigAPony** [amir-khamis/gmc#1]
Consider pulling Identities from ES ldapsearch. Maybe put ES Identities in an index so GMC can access. Then normalize fields as possible.

I copied the identities.csv from ES, created a lookup, added this to your search.
 | lookup ldap_identities_lookup identity AS Identity OUTPUTNEW work_city AS City, phone AS Phone, work_country AS Country, startDate, bunit AS Department, bunit AS Cost_Center, managedBy AS Manager

**Comment by amir-khamis** [comment]
Ok I will include a job that will do that.  This is great!  thanks so much @DigAPony
